### ISSUE TITLE
Possible syntax issues.

### ISSUE THREAD

**Issue by apiszcz** [quantumjot/BayesianTracker#2]
This may be due to setup.py missing however.

```
>>> import btrack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\g\test\lib\btrack\__init__.py", line 3, in <module>
    from core import *
  File "C:\g\test\lib\btrack\core.py", line 602
    self.__motion_model = None
                             ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by quantumjot** [comment]
Thanks! This should be fixed now.
