### ISSUE TITLE
TrackerConfig.json broken by PR that updated linting

### ISSUE THREAD

**Issue by p-j-smith** [quantumjot/BayesianTracker#211]
https://github.com/quantumjot/BayesianTracker/pull/204 has broken the ability to convert `TrackerConfig` to json.

### Steps to reproduce

```python
import btrack
from btrack import datasets

config_file = btrack.datasets.cell_config()
config = btrack.config.load_config(config_file)
config.json()
```

### Output
The following error is raised:
```python
Traceback (most recent call last):
  File "/Users/paul/git/BayesianTracker/tracker_to_json.py", line 6, in <module>
    config.json()
  File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "/Users/paul/mambaforge/envs/napari-btrack/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/paul/mambaforge/envs/napari-btrack/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/paul/mambaforge/envs/napari-btrack/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 103, in pydantic.json.custom_pydantic_encoder
  File "pydantic/json.py", line 90, in pydantic.json.pydantic_encoder
TypeError: Object of type 'ndarray' is not JSON serializable
```

### Suggested solution

I've had a quick look into what is causing the error and it's not clear. The PR was so large and may have inadvertently broken other parts of the code. We could revert all the changes in the PR, add a test for converting `TrackerConfig` to json and writing to file, then start adding back the changes in #204

**Comment by p-j-smith** [comment]
For a bit more context, the reason this issue wasn't picked up in CI is because [the test](https://github.com/quantumjot/BayesianTracker/blob/main/tests/test_config.py#L45-L53) for exporting a `TrackerConfig` uses a [minimal config](https://github.com/quantumjot/BayesianTracker/blob/75945435651b48f4cbc8e2b345add92058c8438c/tests/test_config.py#L13-L21) that has no `MotionModel`, `HypothesisModel`, or `ObjectModel`.  The error is only raised when pydantic attempts to serialise the numpy arrays in these models. Although it's still not clear why there's an error now but not before.
